import '@/assets/styles/reset.css'
import Provider from '@/provider/Provider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './_components/Header/Header'
import styles from './page.module.scss'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    // <Provider>
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className={styles.main}>
          <Provider>{children}</Provider>
        </main>
      </body>
    </html>
    // </Provider>
  )
}
